// <auto-generated />
using LibraryDomain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library.Infrastructure.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20260831184530_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("LibraryDomain.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "IX_Account_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "IX_Account_Username")
                        .IsUnique();

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("LibraryDomain.Models.Book", b =>
                {
                    b.Property<string>("Isbn")
                        .HasColumnType("TEXT")
                        .HasColumnName("ISBN");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BorrowedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Isbn");

                    b.HasIndex("BorrowedBy");

                    b.ToTable("Book", (string)null);
                });

            modelBuilder.Entity("LibraryDomain.Models.Room", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("ID");

                    b.Property<int?>("Bookedby")
                        .HasColumnType("INTEGER")
                        .HasColumnName("BOOKEDBY");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TYPE");

                    b.HasKey("Id");

                    b.HasIndex("Bookedby");

                    b.ToTable("Room", (string)null);
                });

            modelBuilder.Entity("LibraryDomain.Models.Book", b =>
                {
                    b.HasOne("LibraryDomain.Models.Account", "BorrowedByNavigation")
                        .WithMany("Books")
                        .HasForeignKey("BorrowedBy");

                    b.Navigation("BorrowedByNavigation");
                });

            modelBuilder.Entity("LibraryDomain.Models.Room", b =>
                {
                    b.HasOne("LibraryDomain.Models.Account", "BookedbyNavigation")
                        .WithMany("Rooms")
                        .HasForeignKey("Bookedby");

                    b.Navigation("BookedbyNavigation");
                });

            modelBuilder.Entity("LibraryDomain.Models.Account", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
